const express = require('express')
const router = express.Router()
const portfolio = require('../controllers/portfolio')
const auth = require('../middleware/auth')

router.post('/getPortfolio', auth.authenticateToken, auth.userRequired, auth.allowCors(portfolio.getPortfolio))
router.post('/getPortfolioByUsername', auth.allowCors(portfolio.getPortfolioByUsername))
router.post('/getProject', auth.allowCors(portfolio.getProject))
router.post('/hero', auth.authenticateToken, auth.userRequired, auth.allowCors(portfolio.uploadHero))
router.post('/skills', auth.authenticateToken, auth.userRequired, auth.allowCors(portfolio.uploadSkills))
router.post('/services', auth.authenticateToken, auth.userRequired, auth.allowCors(portfolio.uploadServices))
router.post('/addExperience', auth.authenticateToken, auth.userRequired, auth.allowCors(portfolio.addExperience))
router.post('/updateExperience', auth.authenticateToken, auth.userRequired, auth.allowCors(portfolio.updateExperience))
router.post('/addProject', auth.authenticateToken, auth.userRequired, auth.allowCors(portfolio.addProject))
router.post('/updateProject', auth.authenticateToken, auth.userRequired, auth.allowCors(portfolio.updateProject))
router.post('/deleteProject', auth.authenticateToken, auth.userRequired, auth.allowCors(portfolio.deleteProject))
router.post('/uploadContacts', auth.authenticateToken, auth.userRequired, auth.allowCors(portfolio.uploadContacts))
router.post('/testEmail', auth.authenticateToken, auth.userRequired, auth.allowCors(portfolio.testEmail))
router.post('/sendEmail', auth.allowCors(portfolio.sendEmail))
router.post('/sendContactUs', auth.allowCors(portfolio.sendContactUs))
router.post('/education', auth.authenticateToken, auth.userRequired, auth.allowCors(portfolio.uploadEducation))
router.post('/languages', auth.authenticateToken, auth.userRequired, auth.allowCors(portfolio.uploadLanguages))
router.post('/certifications', auth.authenticateToken, auth.userRequired, auth.allowCors(portfolio.uploadCertifications))
router.post('/updateLayout', auth.authenticateToken, auth.userRequired, auth.allowCors(portfolio.updateLayout))
router.post('/publishPortfolio', auth.authenticateToken, auth.userRequired, auth.allowCors(portfolio.publishPortfolio))
router.post('/unpublishPortfolio', auth.authenticateToken, auth.userRequired, auth.allowCors(portfolio.unpublishPortfolio))

module.exports = router
