const express = require('express')
const router = express.Router()
const project = require('../controllers/project')
const auth = require('../middleware/auth')

router.post('/getUserProject', auth.authenticateToken, auth.userRequired, auth.allowCors(project.getUserProject))
router.post('/getAdminCategory', auth.authenticateToken, auth.userRequired, auth.allowCors(project.getAdminCategory))
router.post('/addCategory', auth.authenticateToken, auth.userRequired, auth.allowCors(project.addCategory))
router.post('/editCategory', auth.authenticateToken, auth.userRequired, auth.allowCors(project.editCategory))
router.post('/removeCategory', auth.authenticateToken, auth.userRequired, auth.allowCors(project.removeCategory))
router.post('/uploadProject', auth.authenticateToken, auth.userRequired, auth.allowCors(project.uploadProject))
router.post('/editUserProject', auth.authenticateToken, auth.userRequired, auth.allowCors(project.editUserProject))
router.post('/removeUserProject', auth.authenticateToken, auth.userRequired, auth.allowCors(project.removeUserProject))
router.post('/bulkDeleteProjects', auth.authenticateToken, auth.userRequired, auth.allowCors(project.bulkDeleteProjects))
router.post('/bulkUpdateProjects', auth.authenticateToken, auth.userRequired, auth.allowCors(project.bulkUpdateProjects))

router.post('/addCollaborator', auth.authenticateToken, auth.userRequired, auth.allowCors(project.addCollaborator))
router.post('/removeCollaborator', auth.authenticateToken, auth.userRequired, auth.allowCors(project.removeCollaborator))
router.post('/getProjectAnalytics', auth.authenticateToken, auth.userRequired, auth.allowCors(project.getProjectAnalytics))

router.post('/toggleBookmark', auth.allowCors(project.toggleBookmark))
router.post('/getBookmarkedProjects', auth.allowCors(project.getBookmarkedProjects))
router.post('/getRelatedProjects', auth.allowCors(project.getRelatedProjects))

router.post('/getProjectByID', auth.allowCors(project.getProjectByID))
router.post('/getCategory', auth.allowCors(project.getCategory))
router.post('/getProjects', auth.allowCors(project.getProjects))
router.post('/getProjectsByCategories', auth.allowCors(project.getProjectsByCategories))
router.post('/getProjectsBySearchKey', auth.allowCors(project.getProjectsBySearchKey))
router.post('/projectCountTags', auth.allowCors(project.projectCountTags))
router.post('/getProjectComments', auth.allowCors(project.getProjectComments))
router.post('/uploadProjectComment', auth.allowCors(project.uploadProjectComment))
router.patch('/updateProjectComment', auth.allowCors(project.updateProjectComment))
router.delete('/removeProjectComment/:id/:project_id', auth.allowCors(project.removeProjectComment))
router.post('/toggleProjectLike', auth.allowCors(project.toggleProjectLike))
router.post('/getLatestProjects', auth.allowCors(project.getLatestProjects))
router.post('/viewProject', auth.allowCors(project.viewProject))

module.exports = router
